version: '3'
services:
  api-server:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile
    image: pk2020:latest
    container_name: api-server
    entrypoint:
      - /bin/sh
      - api-command.sh
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    tty: true
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - 3000:3000

  bgr-job:
    image: pk2020:latest
    container_name: bgr-job
    entrypoint:
      - /bin/sh
      - bgr-job-command.sh
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    depends_on:
      - api-server
    tty: true
    volumes:
      - ./public:/usr/src/app/public

  web-server:
    image: pk2020:latest
    container_name: web-server
    entrypoint:
      - /bin/sh
      - web-command.sh
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    depends_on:
      - api-server
    tty: true
    ports:
      - 3001:3001