version: '3'
services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: pk2020:latest
    container_name: node-server
    entrypoint:
      - /bin/sh
      - ./command.sh
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3000
      - SERVER_PROTOCOL=http://
      - SERVER_URI=pk2020.tk
    tty: true
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - 3000:3000

  bgr-job:
    image: pk2020:latest
    container_name: bgr-job
    entrypoint:
      - /bin/sh
      - ./bgr-job-command.sh
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - SERVER_PROTOCOL=http://
      - SERVER_URI=pk2020.tk
      - SERVER_PORT=6789
      - SERVER_PORT_WEB=80
    depends_on:
      - node-server
    tty: true
    volumes:
      - ./public:/usr/src/app/public