version: '3'
services:
  api-server:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile
    image: pk2020:latest
    container_name: api-server
    entrypoint:
      - /bin/sh
      - api-command.sh
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    tty: true
    ports:
      - 3000:3000

  background-job:
    image: pk2020:latest
    container_name: background-job
    entrypoint:
      - /bin/sh
      - background-job-command.sh
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    tty: true
    depends_on:
      - api-server

  web-server:
    image: pk2020:latest
    container_name: web-server
    entrypoint:
      - /bin/sh
      - web-command.sh
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    tty: true
    depends_on:
      - api-server
    ports:
      - 3001:3001