version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
            pip install --upgrade pip
            pip install \
              docker-compose
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
            if [ "${CIRCLE_BRANCH}" == "KLTN2020" ]
            then
              docker tag app "${DOCKERHUB_REPO}:latest"
              docker push "${DOCKERHUB_REPO}:latest"
            fi
