version: '3'
services:
  api-server:
    image: doonpy/kltn2020:latest
    container_name: api-server
    entrypoint:
      - /bin/sh
      - tools/docker/api/command.sh
    restart: unless-stopped
    working_dir: /usr/src/app
    env_file:
      - api-server.config.env
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - database

  background-job:
    image: doonpy/kltn2020:latest
    container_name: background-job
    entrypoint:
      - /bin/sh
      - tools/docker/background-job/command.sh
    restart: unless-stopped
    working_dir: /usr/src/app
    env_file:
      - background-job.config.env
    tty: true
    depends_on:
      - database

  web-server:
    image: doonpy/kltn2020:latest
    container_name: web-server
    entrypoint:
      - /bin/sh
      - tools/docker/web/command.sh
    restart: unless-stopped
    working_dir: /usr/src/app
    env_file:
      - web-server.config.env
    tty: true
    depends_on:
      - api-server
    ports:
      - 3001:3001

  database:
    image: mongo:latest
    container_name: kltn2020-db
    env_file:
      - database.config.env
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
    tty: true
    restart: unless-stopped