name: Docker Image CI

on:
  push:
    branches: [ KLTN2020 ]
  pull_request:
    branches: [ KLTN2020 ]

jobs:
  build-docker-image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build -t app .

      - name: Push to Docker Hub
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          if [ "${VERSION}" == "refs/heads/KLTN2020" ]; then
            docker login -u $DOCKER_ID -p $DOCKER_TOKEN
            BUILD_TAG=${VESION}-${GITHUB_RUN_NUMBER}-$(date +%s)
            docker tag app doonpy/kltn2020:${BUILD_TAG}
            docker push doonpy/kltn2020:${BUILD_TAG}
            docker tag app doonpy/kltn2020:latest
            docker push doonpy/kltn2020:latest
          fi
