name: Docker Image CI

on:
  push:
    branches: [ KLTN2020 ]
  pull_request:
    branches: [ KLTN2020 ]

jobs:
  build-docker-image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker login -u $DOCKER_ID -p $DOCKER_TOKEN
          if [ "${GITHUB_HEAD_REF}" == "KLTN2020" ]; then
            export BUILD_TAG=latest
          else
            export BUILD_TAG=${GITHUB_HEAD_REF}-${GITHUB_RUN_NUMBER}
          fi
          docker build . --file Dockerfile --tag doonpy/kltn2020:$BUILD_TAG
          docker push doonpy/kltn2020:$BUILD_TAG