name: Docker Image CI

on:
  push:
    branches: [ KLTN2020 ]
  pull_request:
    branches: [ KLTN2020 ]

jobs:
  build-docker-image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build -t app .

      - name: Push to Docker Hub
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          VERSION="${GITHUB_REF:11}"
          BUILD_TAG="${VERSION}_${GITHUB_RUN_NUMBER}"

          if [ "${VERSION}" == "KLTN2020" ]; then
            docker login -u ${DOCKER_ID} -p ${DOCKER_TOKEN}
            docker tag app doonpy/kltn2020:${BUILD_TAG}
            docker push doonpy/kltn2020:${BUILD_TAG}
            docker tag app doonpy/kltn2020:latest
            docker push doonpy/kltn2020:latest
          fi
