export const RawDataConstant = {
    TYPE_OF_TRANSACTION: {
        SALE: 0,
        RENT: 1,
    },
    TYPE_OF_PROPERTY_FOR_SALE: {
        APARTMENT: 0,
        INDIVIDUAL_HOUSE: 1,
        VILLA: 2,
        TOWNHOUSE: 3,
        PROJECT_LAND: 4,
        LAND: 5,
        FARM: 6,
        RESORT: 7,
        WAREHOUSE: 8,
        OTHER: 9,
    },
    TYPE_OF_PROPERTY_FOR_RENT: {
        APARTMENT: 0,
        HOUSE: 1,
        TOWNHOUSE: 2,
        ROOM: 3,
        OFFICE: 4,
        SHOP: 5,
        WAREHOUSE: 6,
        OTHER: 7,
    },
    DEFINITION: {
        APARTMENT: ['căn hộ chung cư', 'apartments'],
        INDIVIDUAL_HOUSE: ['nhà riêng', 'individual houses'],
        VILLA: ['biệt thự', 'villas'],
        TOWNHOUSE: ['nhà mặt phố', 'townhouses'],
        PROJECT_LAND: ['đất nền dự án', 'project lands'],
        LAND: ['đất', 'lands'],
        FARM: ['trang trại', 'farms'],
        RESORT: ['khu nghỉ dưỡng', 'resorts'],
        WAREHOUSE: ['nhà kho', 'warehouse'],
        ROOM: ['nhà trọ, phòng trọ', 'rooms'],
        OFFICE: ['văn phòng', 'offices'],
        SHOP: ['cửa hàng', 'shops'],
        OTHER: ['loại bất động sản khác', 'others'],
    },
};
