export const RawDataConstant = {
    TYPE_OF_TRANSACTION: {
        SALE: 0,
        RENT: 1,
    },
    TYPE_OF_PROPERTY: {
        APARTMENT: 0,
        INDIVIDUAL_HOUSE: 1,
        VILLA: 2,
        TOWNHOUSE: 3,
        PROJECT_LAND: 4,
        LAND: 5,
        FARM: 6,
        RESORT: 7,
        WAREHOUSE: 8,
        ROOM: 9,
        OFFICE: 10,
        SHOP: 11,
        OTHER: 12,
    },
    DEFINITION: {
        TYPE_OF_TRANSACTION: [
            ['Bán', 'Sale'],
            ['Thuê', 'Rent'],
        ],
        TYPE_OF_PROPERTY: [
            ['Căn hộ chung cư', 'Apartments'],
            ['Nhà riêng', 'Individual houses'],
            ['Biệt thự', 'Villas'],
            ['Nhà mặt phố', 'Townhouses'],
            ['Đất nền dự án', 'Project lands'],
            ['Đất', 'Lands'],
            ['Trang trại', 'Farms'],
            ['Khu nghỉ dưỡng', 'Resorts'],
            ['Nhà kho', 'Warehouse'],
            ['Nhà trọ, Phòng trọ', 'Rooms'],
            ['Văn phòng', 'Offices'],
            ['Cửa hàng', 'Shops'],
            ['Loại bất động sản khác', 'Others'],
        ],
    },
};
